package model.FaceFeatures;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Created by sargis on 3/29/17.
 */
public class FacePoints {
    HashMap<Integer,String> facepoints;
  //  List <String> facePointsName;
    public static final String mouth_upper_lip_left_contour2="mouth_upper_lip_left_contour2";
    public static final String mouth_upper_lip_left_contour1="mouth_upper_lip_left_contour1";
    public static final String mouth_upper_lip_left_contour3="mouth_upper_lip_left_contour3";
    public static final String mouth_lower_lip_left_contour2="mouth_lower_lip_left_contour2";
    public static final String mouth_upper_lip_right_contour3="mouth_upper_lip_right_contour3";
    public static final String mouth_lower_lip_right_contour1="mouth_lower_lip_right_contour1";
    public static final String mouth_lower_lip_right_contour3="mouth_lower_lip_right_contour3";
    public static final String mouth_lower_lip_right_contour2="mouth_lower_lip_right_contour2";
    public static final String mouth_upper_lip_right_contour1="mouth_upper_lip_right_contour1";
    public static final String mouth_upper_lip_right_contour2="mouth_upper_lip_right_contour2";
    public static final String mouth_lower_lip_left_contour3="mouth_lower_lip_left_contour3";
    public static final String mouth_lower_lip_left_contour1="mouth_lower_lip_left_contour1";
    public static final String mouth_lower_lip_top="mouth_lower_lip_top";
    public static final String mouth_upper_lip_bottom="mouth_upper_lip_bottom";
    public static final String mouth_left_corner="mouth_left_corner";
    public static final String mouth_upper_lip_top="mouth_upper_lip_top";
    public static final String right_eye_lower_left_quarter="right_eye_lower_left_quarter";
    public static final String right_eyebrow_lower_left_quarter="right_eyebrow_lower_left_quarter";
    public static final String right_eye_pupil="right_eye_pupil";
    public static final String right_eyebrow_upper_middle="right_eyebrow_upper_middle";
    public static final String right_eyebrow_left_corner="right_eyebrow_left_corner";
    public static final String right_eye_lower_right_quarter="right_eye_lower_right_quarter";
    public static final String right_eye_bottom="right_eye_bottom";
    public static final String contour_left1="contour_left1";
    public static final String contour_left2="contour_left2";
    public static final String contour_left3="contour_left3";
    public static final String contour_left4="contour_left4";
    public static final String contour_left7="contour_left7";
    public static final String contour_left9="contour_left9";
    public static final String contour_left6="contour_left6";
    public static final String contour_left5="contour_left5";
    public static final String contour_chin="contour_chin";
    public static final String contour_right1="contour_right1";
    public static final String contour_right2="contour_right2";
    public static final String contour_right3="contour_right3";
    public static final String contour_right4="contour_right4";
    public static final String contour_right7="contour_right7";
    public static final String nose_contour_left1="nose_contour_left1";
    public static final String nose_contour_left2="nose_contour_left2";
    public static final String nose_contour_left3="nose_contour_left3";
    public static final String nose_contour_right1="nose_contour_right1";
    public static final String nose_contour_right2="nose_contour_right2";
    public static final String contour_right9="contour_right9";
    public static final String contour_left8="contour_left8";
    public static final String contour_right8="contour_right8";
    public static final String contour_right6="contour_right6";
    public static final String left_eyebrow_lower_left_quarter="left_eyebrow_lower_left_quarter";
    public static final String left_eye_upper_left_quarter="left_eye_upper_left_quarter";
    public static final String left_eyebrow_lower_middle="left_eyebrow_lower_middle";
    public static final String left_eyebrow_left_corner="left_eyebrow_left_corner";
    public static final String left_eye_left_corner="left_eye_left_corner";
    public static final String left_eyebrow_upper_left_quarter="left_eyebrow_upper_left_quarter";
    public static final String left_eye_bottom="left_eye_bottom";
    public static final String left_eye_right_corner="left_eye_right_corner";
    public static final String left_eyebrow_right_corner="left_eyebrow_right_corner";
    public static final String left_eyebrow_lower_right_quarter="left_eyebrow_lower_right_quarter";
    public static final String left_eye_pupil="left_eye_pupil";
    public static final String left_eye_lower_right_quarter="left_eye_lower_right_quarter";
    public static final String left_eyebrow_upper_right_quarter="left_eyebrow_upper_right_quarter";
    public static final String left_eye_upper_right_quarter="left_eye_upper_right_quarter";
    public static final String left_eyebrow_upper_middle="left_eyebrow_upper_middle";
    public static final String left_eye_top="left_eye_top";
    public static final String left_eye_lower_left_quarter="left_eye_lower_left_quarter";
    public static final String left_eye_center="left_eye_center";
    public static final String mouth_right_corner="mouth_right_corner";
    public static final String nose_contour_lower_middle="nose_contour_lower_middle";
    public static final String nose_contour_right3="nose_contour_right3";
    public static final String nose_left="nose_left";
    public static final String nose_right="nose_right";
    public static final String nose_tip="nose_tip";
    public static final String right_eye_left_corner="right_eye_left_corner";
    public static final String right_eyebrow_upper_left_quarter="right_eyebrow_upper_left_quarter";
    public static final String right_eye_center="right_eye_center";
    public static final String right_eyebrow_right_corner="right_eyebrow_right_corner";
    public static final String right_eye_upper_left_quarter="right_eye_upper_left_quarter";
    public static final String right_eyebrow_upper_right_quarter="right_eyebrow_upper_right_quarter";
    public static final String right_eye_upper_right_quarter="right_eye_upper_right_quarter";
    public static final String right_eyebrow_lower_middle="right_eyebrow_lower_middle";
    public static final String right_eye_top="right_eye_top";
    public static final String right_eye_right_corner="right_eye_right_corner";
    public static final String right_eyebrow_lower_right_quarter="right_eyebrow_lower_right_quarter";

    public FacePoints()
    {
        facepoints=new   HashMap<Integer,String>();
       // facePointsName =new ArrayList<>();
    }
    public List<String> getFacepointNames()
    {
        List<String> facePointsName =new ArrayList<>();
        //mouth_upper_lip_left_contour2="mouth_upper_lip_left_contour2";
        facePointsName.add(mouth_upper_lip_left_contour2);
        facePointsName.add(mouth_upper_lip_left_contour1);
        facePointsName.add(mouth_upper_lip_top);
        facePointsName.add(mouth_upper_lip_left_contour3);
        facePointsName.add(mouth_left_corner);
        facePointsName.add(mouth_lower_lip_right_contour1);
        facePointsName.add(mouth_lower_lip_left_contour2);
        facePointsName.add(mouth_lower_lip_right_contour3);
        facePointsName.add(mouth_lower_lip_right_contour2);
        facePointsName.add(mouth_upper_lip_right_contour1);
        facePointsName.add(mouth_upper_lip_right_contour2);
        facePointsName.add(mouth_lower_lip_left_contour3);
        facePointsName.add(mouth_lower_lip_left_contour1);
        facePointsName.add(mouth_lower_lip_top);
        facePointsName.add(mouth_upper_lip_bottom);
        facePointsName.add(mouth_upper_lip_right_contour3);
        facePointsName.add(right_eye_lower_left_quarter);
        facePointsName.add(right_eyebrow_lower_left_quarter);
        facePointsName.add(right_eye_pupil);
        facePointsName.add(right_eyebrow_upper_middle);
        facePointsName.add(right_eyebrow_left_corner);
        facePointsName.add(right_eye_lower_right_quarter);
        facePointsName.add(right_eye_bottom);
        facePointsName.add(contour_left7);
        facePointsName.add(contour_left6);
        facePointsName.add(contour_left5);
        facePointsName.add(contour_left4);
        facePointsName.add(contour_left3);
        facePointsName.add(contour_left2);
        facePointsName.add(contour_left1);
        facePointsName.add(contour_chin);
        facePointsName.add(contour_left9);
        facePointsName.add(contour_right1);
        facePointsName.add(contour_right2);
        facePointsName.add(contour_right3);
        facePointsName.add(contour_right4);
        facePointsName.add(contour_right7);
        facePointsName.add(nose_contour_left1);
        facePointsName.add(nose_contour_left2);
        facePointsName.add(nose_contour_left3);
        facePointsName.add(nose_contour_right1);
        facePointsName.add(nose_contour_right2);
        facePointsName.add(contour_right9);
        facePointsName.add(contour_right8);
        facePointsName.add(contour_right6);
        facePointsName.add(contour_left8);
        facePointsName.add(left_eyebrow_lower_left_quarter);
        facePointsName.add(left_eye_upper_left_quarter);
        facePointsName.add(left_eyebrow_lower_middle);
        facePointsName.add(left_eyebrow_left_corner);
        facePointsName.add(left_eye_left_corner);
        facePointsName.add(left_eyebrow_upper_left_quarter);
        facePointsName.add(left_eye_bottom);
        facePointsName.add(left_eye_right_corner);
        facePointsName.add(left_eyebrow_right_corner);
        facePointsName.add(left_eyebrow_lower_right_quarter);
        facePointsName.add(left_eye_pupil);
        facePointsName.add(left_eye_lower_right_quarter);
        facePointsName.add(left_eyebrow_upper_right_quarter);
        facePointsName.add( left_eye_upper_right_quarter);
        facePointsName.add( left_eyebrow_upper_middle);
        facePointsName.add( left_eye_top);
        facePointsName.add( left_eye_lower_left_quarter);
        facePointsName.add( left_eye_center);
        facePointsName.add(mouth_right_corner);
        facePointsName.add(nose_contour_lower_middle);
        facePointsName.add(nose_contour_right3);
        facePointsName.add(nose_left);
        facePointsName.add(nose_right);
        facePointsName.add(nose_tip);
        facePointsName.add(right_eye_left_corner);
        facePointsName.add(right_eyebrow_upper_left_quarter);
        facePointsName.add(right_eye_center);
        facePointsName.add(right_eyebrow_right_corner);
        facePointsName.add(right_eye_upper_left_quarter);
        facePointsName.add(right_eyebrow_right_corner);
        facePointsName.add(right_eyebrow_upper_right_quarter);
        facePointsName.add(right_eye_upper_right_quarter);
        facePointsName.add( right_eyebrow_lower_middle);
        facePointsName.add( right_eye_top);
        facePointsName.add( right_eye_right_corner);
        facePointsName.add(right_eyebrow_lower_right_quarter);
        return facePointsName;
    }
}
